// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacramentMeetingPlannerTY.Models;
using System;

namespace SacramentMeetingPlannerTY.Migrations
{
    [DbContext(typeof(SacramentMeetingPlannerTYContext))]
    [Migration("20180412144855_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentMeetingPlannerTY.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bishopric");

                    b.Property<string>("ClosingHymn");

                    b.Property<string>("ClosingPrayer");

                    b.Property<string>("FirstSpeaker");

                    b.Property<string>("FourthSpeaker");

                    b.Property<string>("IntermediateHymn");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<string>("OpeningHymn");

                    b.Property<string>("OpeningPray");

                    b.Property<string>("SacramentHymn");

                    b.Property<string>("SecondSpeaker");

                    b.Property<string>("ThirdSpeaker");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
