// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacramentMeetingPlannerTY.Models;
using System;

namespace SacramentMeetingPlannerTY.Migrations
{
    [DbContext(typeof(SacramentMeetingPlannerTYContext))]
    partial class SacramentMeetingPlannerTYContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentMeetingPlannerTY.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bishopric")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ClosingHymn")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ClosingPrayer")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("FirstSpeaker")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("FirstTopic")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("FourthSpeaker")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("FourthTopic")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("IntermediateHymn")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<DateTime>("MeetingDate");

                    b.Property<string>("OpeningHymn")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("OpeningPray")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("SacramentHymn")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("SecondSpeaker")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("SecondTopic")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ThirdSpeaker")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ThirdTopic")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
